// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.github.rfoltyns.vertx.grpc;

public final class GrpcProto {
  private GrpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_rfoltyns_vertx_grpc_MeasureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_rfoltyns_vertx_grpc_MeasureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_rfoltyns_vertx_grpc_MeasureRequest_SampleMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_rfoltyns_vertx_grpc_MeasureRequest_SampleMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_rfoltyns_vertx_grpc_MeasureReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_rfoltyns_vertx_grpc_MeasureReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021GrpcService.proto\022\036com.github.rfoltyns" +
      ".vertx.grpc\"\277\002\n\016MeasureRequest\022\n\n\002id\030\001 \001" +
      "(\005\022\020\n\010consumer\030\002 \001(\t\022\021\n\tcreatedAt\030\003 \001(\003\022" +
      "\022\n\nreceivedAt\030\004 \001(\003\022\023\n\013processedAt\030\005 \001(\003" +
      "\022\023\n\013delayMillis\030\006 \001(\005\022\026\n\016delayDeviation\030" +
      "\007 \001(\005\022\024\n\014numberOfHops\030\010 \001(\005\022\014\n\004data\030\t \001(" +
      "\014\022P\n\tsampleMap\030\n \003(\0132=.com.github.rfolty" +
      "ns.vertx.grpc.MeasureRequest.SampleMapEn" +
      "try\0320\n\016SampleMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t:\0028\001\"V\n\014MeasureReply\022\n\n\002id\030\001 \001(",
      "\005\022\021\n\tcreatedAt\030\003 \001(\003\022\022\n\nreceivedAt\030\004 \001(\003" +
      "\022\023\n\013processedAt\030\005 \001(\0032u\n\010Receiver\022i\n\007Mea" +
      "sure\022..com.github.rfoltyns.vertx.grpc.Me" +
      "asureRequest\032,.com.github.rfoltyns.vertx" +
      ".grpc.MeasureReply\"\000B-\n\036com.github.rfolt" +
      "yns.vertx.grpcB\tGrpcProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_rfoltyns_vertx_grpc_MeasureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_rfoltyns_vertx_grpc_MeasureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_rfoltyns_vertx_grpc_MeasureRequest_descriptor,
        new java.lang.String[] { "Id", "Consumer", "CreatedAt", "ReceivedAt", "ProcessedAt", "DelayMillis", "DelayDeviation", "NumberOfHops", "Data", "SampleMap", });
    internal_static_com_github_rfoltyns_vertx_grpc_MeasureRequest_SampleMapEntry_descriptor =
      internal_static_com_github_rfoltyns_vertx_grpc_MeasureRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_github_rfoltyns_vertx_grpc_MeasureRequest_SampleMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_rfoltyns_vertx_grpc_MeasureRequest_SampleMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_github_rfoltyns_vertx_grpc_MeasureReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_rfoltyns_vertx_grpc_MeasureReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_rfoltyns_vertx_grpc_MeasureReply_descriptor,
        new java.lang.String[] { "Id", "CreatedAt", "ReceivedAt", "ProcessedAt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
