// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.github.rfoltyns.vertx.grpc;

public interface MeasureReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.rfoltyns.vertx.grpc.MeasureReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>int64 createdAt = 3;</code>
   */
  long getCreatedAt();

  /**
   * <code>int64 receivedAt = 4;</code>
   */
  long getReceivedAt();

  /**
   * <code>int64 processedAt = 5;</code>
   */
  long getProcessedAt();
}
