// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.github.rfoltyns.vertx.grpc;

public interface MeasureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.rfoltyns.vertx.grpc.MeasureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string consumer = 2;</code>
   */
  java.lang.String getConsumer();
  /**
   * <code>string consumer = 2;</code>
   */
  com.google.protobuf.ByteString
      getConsumerBytes();

  /**
   * <code>int64 createdAt = 3;</code>
   */
  long getCreatedAt();

  /**
   * <code>int64 receivedAt = 4;</code>
   */
  long getReceivedAt();

  /**
   * <code>int64 processedAt = 5;</code>
   */
  long getProcessedAt();

  /**
   * <code>int32 delayMillis = 6;</code>
   */
  int getDelayMillis();

  /**
   * <code>int32 delayDeviation = 7;</code>
   */
  int getDelayDeviation();

  /**
   * <code>int32 numberOfHops = 8;</code>
   */
  int getNumberOfHops();

  /**
   * <code>bytes data = 9;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>map&lt;string, string&gt; sampleMap = 10;</code>
   */
  int getSampleMapCount();
  /**
   * <code>map&lt;string, string&gt; sampleMap = 10;</code>
   */
  boolean containsSampleMap(
      java.lang.String key);
  /**
   * Use {@link #getSampleMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getSampleMap();
  /**
   * <code>map&lt;string, string&gt; sampleMap = 10;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getSampleMapMap();
  /**
   * <code>map&lt;string, string&gt; sampleMap = 10;</code>
   */

  java.lang.String getSampleMapOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; sampleMap = 10;</code>
   */

  java.lang.String getSampleMapOrThrow(
      java.lang.String key);
}
